spring.application.name=spring-mysql-learning
spring.datasource.url=jdbc:mysql://localhost:3306/learning_db
spring.datasource.username=root
spring.datasource.password=Ankit@12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
jwt.secret=${JWT_SECRET}
logging.level.org.springframework.web=DEBUG